name: v3_cap_web
description: A professional cinematic camera app for the web.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # These are the only packages needed for a robust web camera app
  camera_web: ^0.3.3
  camera_platform_interface: ^2.7.4
  image: ^4.1.3
  url_launcher: ^6.2.6
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
